# Generated by Django 4.2.9 on 2025-04-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_category_user_gender_user_porfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='porfile',
            new_name='profile',
        ),
    ]
